#define PWM_PIN GPIO_NUM_33
#define TM1637_CLK_PIN GPIO_NUM_18
#define TM1637_DIO_PIN GPIO_NUM_19
#define BEEP_PIN GPIO_NUM_17
#define STRIKE_1_PIN GPIO_NUM_4
#define STRIKE_2_PIN GPIO_NUM_16
#define STRIKE_3_PIN GPIO_NUM_2
#define MORSE_PIN GPIO_NUM_0

#define STRIKE_BTN GPIO_NUM_33

#define SOUND_ON true
